vich_uploader:
    db_driver: orm
    mappings:
        portfolio_images:
            uri_prefix: '%app.path.portfolio_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.portfolio_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
