easy_admin:
  entities:
    Experiences:
      class: App\Entity\Experiences
      list:
        title: "All experiences"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','title', 'description']
      show:
        fields:
          - {property: 'title'}
          - {property: 'description', type: 'raw'}
      form:
        fields:
          - {type: 'group', label: 'General',icon: 'pencil', css_class: 'col-md-8'}
          - {property: 'title'}
          - {type: 'section'}
          - {property: 'description', type: 'text_editor',label: 'Description de experience'}
