easy_admin:
  entities:
    Skills:
      class: App\Entity\Skills
      list:
        title: "All skills"
        collapse_actions: true
        actions: ['show','edit','delete']
        fields: ['id','title', 'description', 'thumbnail', 'createdAt','updatedAt']
      show:
        fields:
          - {property: 'title'}
          - {property: 'description', type: 'raw'}
          - {property: 'createdAt'}
          - {property: 'updatedAt'}
          - {property: 'thumbnail'}
      form:
        fields:
          - {type: 'group', label: 'General',icon: 'pencil', css_class: 'col-md-8'}
          - {property: 'title'}
          - {property: 'createdAt', type_options: { widget: 'single_text' }}
          - {property: 'updatedAt', type_options: { widget: 'single_text' }}
          - {type: 'section'}
          - {property: 'description', type: 'text_editor',label: 'Description de la competence'}
          - {type: 'group', label: 'Thumbnail',css_class: 'col-md-4'}
          - {property: 'thumbnail'}
